export const login_path = "/users/login"
export const tours_all = "/Tour/"
export const cities_all = "/admin/City/"
export const tour_booking = "/TourBooking/"
export const tour_spot_all = "/admin/TourSpot/"
